In [4]:
import pandas as pd
import numpy as np

data = np.random.rand(3, 4) # row, column
print(data)

[[0.3857201  0.465476   0.07190713 0.90717523]
 [0.62400624 0.76970064 0.44919913 0.44680153]
 [0.21054095 0.37881681 0.08590543 0.46644336]]


In [5]:
dataFrame = pd.DataFrame(data, index=[1, 2, 3], columns=['c1','c2','c3','c4'])
print(dataFrame)

         c1        c2        c3        c4
1  0.385720  0.465476  0.071907  0.907175
2  0.624006  0.769701  0.449199  0.446802
3  0.210541  0.378817  0.085905  0.466443


In [6]:
# Data frame 2
# Arranging index and adding new rows with null values
newFrame =  dataFrame.reindex([1, 4, 2, 3])
print(newFrame)

         c1        c2        c3        c4
1  0.385720  0.465476  0.071907  0.907175
4       NaN       NaN       NaN       NaN
2  0.624006  0.769701  0.449199  0.446802
3  0.210541  0.378817  0.085905  0.466443


In [7]:
# Check if value of coloum is null
print(newFrame['c2'].isnull())
print(newFrame[newFrame['c2'].isnull()])

1    False
4     True
2    False
3    False
Name: c2, dtype: bool
   c1  c2  c3  c4
4 NaN NaN NaN NaN


In [8]:
# Replace missing data
print(newFrame['c2'].fillna("Zuhair"))

1    0.465476
4      Zuhair
2    0.769701
3    0.378817
Name: c2, dtype: object


In [9]:
#Drop missing data
print(newFrame['c1'].dropna())

1    0.385720
2    0.624006
3    0.210541
Name: c1, dtype: float64


In [10]:
#Fill the null data in columns with specific value
for col in newFrame:
    newFrame[col] = newFrame[col].fillna('filled')
print(newFrame)

         c1        c2         c3        c4
1   0.38572  0.465476  0.0719071  0.907175
4    filled    filled     filled    filled
2  0.624006  0.769701   0.449199  0.446802
3  0.210541  0.378817  0.0859054  0.466443


In [12]:
# Change specific column index
newFrame['c1'][2] = 'Specific value'
print(newFrame)

               c1        c2         c3        c4
1         0.38572  0.465476  0.0719071  0.907175
4          filled    filled     filled    filled
2  Specific value  0.769701   0.449199  0.446802
3        0.210541  0.378817  0.0859054  0.466443


In [13]:
# Replace specific value
print(newFrame.replace('filled', 'replace'))

               c1        c2         c3        c4
1         0.38572  0.465476  0.0719071  0.907175
4         replace   replace    replace   replace
2  Specific value  0.769701   0.449199  0.446802
3        0.210541  0.378817  0.0859054  0.466443
